# Importing Libraries

In [63]:
import numpy as np
import pandas as pd

# Data Loading

In [65]:
data = pd.read_csv("FD.csv")
data.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0

# No of Columns

In [67]:
data.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date',
       'Transaction_Amount', 'Merchant_Category', 'Payment_Method',
       'Device_Type', 'Location', 'Is_International', 'Previous_Transactions',
       'Average_Spend', 'Account_Age_Days', 'Suspicious_Keyword',
       'Fraudulent'],
      dtype='object')

In [69]:
data.describe()

,Transaction_Amount,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Fraudulent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,79.180664,0.088200,99.414000,258.377132,1011.158200,0.096400
std,78.964045,0.283614,57.022968,140.230639,568.633834,0.295169
min,0.000000,0.000000,1.000000,10.010000,30.000000,0.000000
25%,22.365000,0.000000,50.000000,138.772500,530.000000,0.000000
50%,55.455000,0.000000,100.000000,261.810000,1012.500000,0.000000
75%,110.297500,0.000000,148.000000,378.525000,1496.000000,0.000000
max,653.800000,1.000000,199.000000,499.990000,1999.000000,1.000000

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Transaction_ID         5000 non-null   object
 1   Customer_ID            5000 non-null   object
 2   Transaction_Date       5000 non-null   object
 3   Transaction_Amount     5000 non-null   float64
 4   Merchant_Category      5000 non-null   object
 5   Payment_Method         5000 non-null   object
 6   Device_Type            5000 non-null   object
 7   Location               5000 non-null   object
 8   Is_International       5000 non-null   int64
 9   Previous_Transactions  5000 non-null   int64
 10  Average_Spend          5000 non-null   float64
 11  Account_Age_Days       5000 non-null   int64
 12  Suspicious_Keyword     5000 non-null   object
 13  Fraudulent             5000 non-null   int64
dtypes: float64(2), int64(4), object(8)
memory usage: 547.0+ KB

In [73]:
df = pd.DataFrame(data)
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0

In [74]:
df.shape

(5000, 14)

# Number of Missing Values

In [77]:
Missing_values = df.isnull().sum()
mv = pd.DataFrame(Missing_values)
mv

                       0
Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Amount     0
Merchant_Category      0
Payment_Method         0
Device_Type            0
Location               0
Is_International       0
Previous_Transactions  0
Average_Spend          0
Account_Age_Days       0
Suspicious_Keyword     0
Fraudulent             0

In [78]:
numerical_columns = df['Transaction_Amount'] = df['Transaction_Amount'].fillna(
    df['Transaction_Amount'].median()
)

numerical_columns.head()

0     37.54
1    240.81
2    105.34
3     73.04
4     13.57
Name: Transaction_Amount, dtype: float64

In [79]:
categorical_columns = df['Payment_Method'] = df['Payment_Method'].fillna(
    df['Payment_Method'].mode()[0]
)

categorical_columns

0            PayPal
1            PayPal
2        Debit Card
3        NetBanking
4       Credit Card
           ...
4995     Debit Card
4996    Credit Card
4997     Debit Card
4998     Debit Card
4999            UPI
Name: Payment_Method, Length: 5000, dtype: object

# Encoding

In [107]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load Dataset
df = pd.read_csv("FD.csv")

# Convert Date Column
df['Transaction_Date'] = pd.to_datetime(
    df['Transaction_Date'],
    format='%d-%m-%Y %H:%M',
    errors='coerce'
)

# Feature Engineering
df['Hour'] = df['Transaction_Date'].dt.hour
df['Day'] = df['Transaction_Date'].dt.day_name()

# Remove Duplicates
df.drop_duplicates(inplace=True)

# Encoding
le = LabelEncoder()

cat_cols = [
    'Merchant_Category',
    'Payment_Method',
    'Device_Type',
    'Location',
    'Suspicious_Keyword'
]

for col in cat_cols:
    df[col] = le.fit_transform(df[col])

 # Save mapping
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))

    label_mappings[col] = mapping


# ==========================================
# PRINT ALL MAPPINGS
# ==========================================
for col, mapping in label_mappings.items():

    print(f"\n===== {col} =====")

    for category, label in mapping.items():
        print(f"{category} --> {label}")

===== Merchant_Category =====
Electronics --> 0
Entertainment --> 1
Fashion --> 2
Food --> 3
Grocery --> 4
Health --> 5
Travel --> 6
Utilities --> 7

===== Payment_Method =====
Credit Card --> 0
Debit Card --> 1
NetBanking --> 2
PayPal --> 3
UPI --> 4

===== Device_Type =====
Desktop --> 0
Mobile --> 1
POS --> 2

===== Location =====
Bengaluru --> 0
Chennai --> 1
Delhi --> 2
Hyderabad --> 3
Kolkata --> 4
Mumbai --> 5
Pune --> 6

===== Suspicious_Keyword =====
No --> 0
Yes --> 1

# Saving CSV

In [111]:
# Save New CSV
df.to_csv("fraud_detection_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!