# Importing Libraries

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset Loading

In [24]:
data = pd.read_csv("FD.csv")
data

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,T104995,CUST3702,01-08-2023 21:20,182.15,Electronics,Debit Card,Mobile,Kolkata,0,13,277.99,840,No,0
4996,T104996,CUST6007,14-01-2024 16:42,10.17,Fashion,Credit Card,Desktop,Chennai,0,128,477.24,441,No,0
4997,T104997,CUST6812,09-01-2023 22:14,31.78,Grocery,Debit Card,Mobile,Kolkata,1,76,442.62,1474,No,1
4998,T104998,CUST9120,18-08-2023 17:15,135.31,Utilities,Debit Card,Mobile,Bengaluru,0,13,73.33,246,No,0
4999,T104999,CUST1080,07-09-2023 21:20,72.77,Entertainment,UPI,Mobile,Bengaluru,0,146,30.23,699,No,0

In [26]:
df = pd.DataFrame(data)
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent
0,T100000,CUST3252,04-10-2023 07:45,37.54,Travel,PayPal,POS,Bengaluru,0,94,417.40,1492,No,0
1,T100001,CUST1630,26-09-2023 08:29,240.81,Utilities,PayPal,Mobile,Bengaluru,0,76,335.47,66,No,0
2,T100002,CUST7852,18-07-2023 15:54,105.34,Entertainment,Debit Card,Mobile,Bengaluru,0,60,432.03,216,No,0
3,T100003,CUST4892,16-10-2023 17:10,73.04,Utilities,NetBanking,Desktop,Kolkata,0,68,488.30,449,No,0
4,T100004,CUST8831,09-09-2023 00:46,13.57,Utilities,Credit Card,Desktop,Bengaluru,0,57,437.03,754,No,0

In [5]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date',
       'Transaction_Amount', 'Merchant_Category', 'Payment_Method',
       'Device_Type', 'Location', 'Is_International', 'Previous_Transactions',
       'Average_Spend', 'Account_Age_Days', 'Suspicious_Keyword',
       'Fraudulent'],
      dtype='object')

# Understanding the Columns

| Column                | Meaning                       |
| --------------------- | ----------------------------- |
| Transaction_ID        | Unique transaction identifier |
| Customer_ID           | Unique customer identifier    |
| Transaction_Date      | Date/time of transaction      |
| Transaction_Amount    | Amount spent                  |
| Merchant_Category     | Type of merchant              |
| Payment_Method        | Card/UPI/Wallet etc.          |
| Device_Type           | Mobile/Desktop/Tablet         |
| Location              | Transaction location          |
| Is_International      | 1 = international transaction |
| Previous_Transactions | Past transaction count        |
| Average_Spend         | Customer average spend        |
| Account_Age_Days      | Customer account age          |
| Suspicious_Keyword    | Fraud-related keyword         |
| Fraudulent            | Target column (0/1)           |

In [7]:
df.describe()

,Transaction_Amount,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Fraudulent
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,79.180664,0.088200,99.414000,258.377132,1011.158200,0.096400
std,78.964045,0.283614,57.022968,140.230639,568.633834,0.295169
min,0.000000,0.000000,1.000000,10.010000,30.000000,0.000000
25%,22.365000,0.000000,50.000000,138.772500,530.000000,0.000000
50%,55.455000,0.000000,100.000000,261.810000,1012.500000,0.000000
75%,110.297500,0.000000,148.000000,378.525000,1496.000000,0.000000
max,653.800000,1.000000,199.000000,499.990000,1999.000000,1.000000

In [8]:
df.tail()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent
4995,T104995,CUST3702,01-08-2023 21:20,182.15,Electronics,Debit Card,Mobile,Kolkata,0,13,277.99,840,No,0
4996,T104996,CUST6007,14-01-2024 16:42,10.17,Fashion,Credit Card,Desktop,Chennai,0,128,477.24,441,No,0
4997,T104997,CUST6812,09-01-2023 22:14,31.78,Grocery,Debit Card,Mobile,Kolkata,1,76,442.62,1474,No,1
4998,T104998,CUST9120,18-08-2023 17:15,135.31,Utilities,Debit Card,Mobile,Bengaluru,0,13,73.33,246,No,0
4999,T104999,CUST1080,07-09-2023 21:20,72.77,Entertainment,UPI,Mobile,Bengaluru,0,146,30.23,699,No,0

#### For Fraud Detection project, using Pandas queries to extract business insights is extremely important because these insights can later be shown in:

Streamlit dashboard

Project report

Resume explanations

Interview discussions

Below are useful and industry-level Pandas queries specifically for fraud analysis.

# After the Label Encoding the values are

In [17]:
from sklearn.preprocessing import LabelEncoder

# Store mappings
label_mappings = {}

cat_cols = [
    'Merchant_Category',
    'Payment_Method',
    'Device_Type',
    'Location',
    'Suspicious_Keyword'
]

# Encoding + Saving Mapping
for col in cat_cols:

    le = LabelEncoder()

    df[col] = le.fit_transform(df[col])

    # Save mapping
    mapping = dict(zip(le.classes_, le.transform(le.classes_)))

    label_mappings[col] = mapping


# ==========================================
# PRINT ALL MAPPINGS
# ==========================================
for col, mapping in label_mappings.items():

    print(f"\n===== {col} =====")

    for category, label in mapping.items():
        print(f"{category} --> {label}")

===== Merchant_Category =====
Electronics --> 0
Entertainment --> 1
Fashion --> 2
Food --> 3
Grocery --> 4
Health --> 5
Travel --> 6
Utilities --> 7

===== Payment_Method =====
Credit Card --> 0
Debit Card --> 1
NetBanking --> 2
PayPal --> 3
UPI --> 4

===== Device_Type =====
Desktop --> 0
Mobile --> 1
POS --> 2

===== Location =====
Bengaluru --> 0
Chennai --> 1
Delhi --> 2
Hyderabad --> 3
Kolkata --> 4
Mumbai --> 5
Pune --> 6

===== Suspicious_Keyword =====
No --> 0
Yes --> 1

# Total Fraudulent Transactions

In [28]:
tf = df[df['Fraudulent'] == 1].shape[0]
print(f"Total Fraud Transaction : {tf}")

Total Fraud Transaction : 482

# Fraud Percentage

In [31]:
fraud_percentage = (
    df['Fraudulent'].mean()
) * 100

print(f"Fraud Percentage : {fraud_percentage}")

Fraud Percentage : 9.64

# Average Fraud Transaction Amount

In [34]:
fta = df[df['Fraudulent'] == 1]['Transaction_Amount'].mean()
print(f"Average Fraud Transaction Amount : {fta:.3f}")

Average Fraud Transaction Amount : 81.994

In [36]:
df[df['Fraudulent'] == 0]['Transaction_Amount'].mean()

78.8805577689243

# Highest Fraudulent Transaction

In [39]:
hft = df[df['Fraudulent'] == 1]['Transaction_Amount'].max()
print(f"High Fraud Transaction : {hft:.3f}")

High Fraud Transaction : 653.800

# Payment Method Most Used in Fraud

In [42]:
pm = df[df['Fraudulent'] == 1][
    'Merchant_Category'
].value_counts()

pmf = pd.DataFrame(pm)
pmf

                   count
Merchant_Category
Food                  74
Entertainment         72
Fashion               62
Health                61
Grocery               58
Travel                56
Utilities             50
Electronics           49

# International Fraud Transactions

In [45]:
ifs = df[
    (df['Is_International'] == 1) &
    (df['Fraudulent'] == 1)
].shape[0]

print(f"Number of International Fraud Transactions are : {ifs}")

Number of International Fraud Transactions are : 163

# Fraud Rate in International Transactions

In [48]:
international = df[
    df['Is_International'] == 1
]

rate = (
    international['Fraudulent'].mean()
) * 100

print(f"Fraud Rate in International Transactions are : {rate:.1f} %")

Fraud Rate in International Transactions are : 37.0 %

# Top Locations with Fraud

In [56]:
locations = df[df['Fraudulent'] == 1][
    'Location'
].value_counts().head(10)

TL = pd.DataFrame(locations)
TL

           count
Location
Mumbai        78
Kolkata       73
Bengaluru     71
Chennai       69
Delhi         65
Hyderabad     64
Pune          62

# Customers with Highest Fraud Amount

In [65]:
CH = df[df['Fraudulent'] == 1].groupby(
    'Customer_ID'
)['Transaction_Amount'].sum().sort_values(
    ascending=False
).head(10)

CHA = pd.DataFrame(CH)
print("Suspicious Customer")
CHA

Suspicious Customer

             Transaction_Amount
Customer_ID
CUST9184                 653.80
CUST1529                 617.88
CUST9095                 512.44
CUST5301                 487.72
CUST2951                 463.39
CUST7322                 421.75
CUST6917                 399.92
CUST1364                 387.63
CUST3683                 385.89
CUST6250                 368.85

# Fraud During Late Night

In [69]:
df['Hour'] = pd.to_datetime(
    df['Transaction_Date'], format='%d-%m-%Y %H:%M',
    errors='coerce'
).dt.hour

In [74]:
late_night_fraud = df[
    (df['Hour'] >= 0) &
    (df['Hour'] <= 5) &
    (df['Fraudulent'] == 1)
]

print(f"Fraud During Late Night : {late_night_fraud.shape[0]}")

Fraud During Late Night : 313

# Transactions Above Average Spend

In [87]:
ta = df[
    df['Transaction_Amount'] >
    df['Average_Spend']
].shape[0]

print(F"Transactions Above Average Spend are : {ta}")

Transactions Above Average Spend are : 672

### Fraud among them:

In [89]:
fa = df[
    (df['Transaction_Amount'] >
     df['Average_Spend']) &
    (df['Fraudulent'] == 1)
].shape[0]

print(f"Fraud Among Them are : {fa}")

Fraud Among Them are : 64

# Top Suspicious Keywords

In [95]:
ts = df[df['Fraudulent'] == 1][
    'Suspicious_Keyword'
].value_counts()

tsk = pd.DataFrame(ts)
tsk

                    count
Suspicious_Keyword
No                    359
Yes                   123

# Fraud Trend by Day

In [101]:
df['Day'] = pd.to_datetime(
    df['Transaction_Date'], format='%d-%m-%Y %H:%M',
    errors='coerce'
).dt.day_name()

ft = df.groupby('Day')[
    'Fraudulent'
].sum().sort_values(
    ascending=False
)

ftd = pd.DataFrame(ft)
ftd

           Fraudulent
Day
Monday             79
Sunday             75
Wednesday          75
Thursday           73
Tuesday            71
Saturday           56
Friday             53

In [106]:
df['Month'] = pd.to_datetime(
    df['Transaction_Date'], format='%d-%m-%Y %H:%M',
    errors='coerce'
).dt.month

fm = df.groupby('Month')[
    'Fraudulent'
].sum()

ftm = pd.DataFrame(fm)
ftm

       Fraudulent
Month
1              71
2              53
3              36
4              36
5              31
6              30
7              40
8              32
9              40
10             51
11             31
12             31

# Correlation with Fraud

In [110]:
numeric_df = df.select_dtypes(include='number')

cf = numeric_df.corr()['Fraudulent'].sort_values(
    ascending=False
)

cwf = pd.DataFrame(cf)
cwf

                       Fraudulent
Fraudulent               1.000000
Is_International         0.287913
Transaction_Amount       0.011637
Account_Age_Days         0.008563
Spend_Deviation          0.004792
Month                    0.002594
Average_Spend            0.001114
Previous_Transactions   -0.014649
Hour                    -0.234765

# Top 10 High-Risk Transactions

In [113]:
df[df['Fraudulent'] == 1].sort_values(
    by='Transaction_Amount',
    ascending=False
).head(10)

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Amount,Merchant_Category,Payment_Method,Device_Type,Location,Is_International,Previous_Transactions,Average_Spend,Account_Age_Days,Suspicious_Keyword,Fraudulent,Hour,Spend_Deviation,Day,Month
531,T100531,CUST9184,25-07-2023 00:29,653.80,Grocery,PayPal,Mobile,Hyderabad,0,95,152.28,1630,No,1,0,501.52,Tuesday,7
3649,T103649,CUST1529,08-01-2024 13:07,617.88,Food,UPI,POS,Bengaluru,0,84,314.26,1133,No,1,13,303.62,Monday,1
1954,T101954,CUST9095,18-12-2023 03:30,512.44,Electronics,Debit Card,Mobile,Chennai,1,22,408.28,1077,No,1,3,104.16,Monday,12
4256,T104256,CUST5301,24-05-2023 02:26,487.72,Health,PayPal,Desktop,Kolkata,0,7,484.01,1299,No,1,2,3.71,Wednesday,5
4559,T104559,CUST2951,23-07-2023 03:23,463.39,Electronics,Credit Card,Desktop,Hyderabad,0,99,417.74,153,No,1,3,45.65,Sunday,7
1715,T101715,CUST7322,15-10-2023 09:16,421.75,Travel,Credit Card,Mobile,Chennai,0,69,254.65,906,Yes,1,9,167.10,Sunday,10
2836,T102836,CUST6917,07-01-2024 01:31,399.92,Food,UPI,POS,Hyderabad,1,51,314.28,1975,No,1,1,85.64,Sunday,1
4765,T104765,CUST1364,25-04-2023 04:15,387.63,Grocery,UPI,POS,Mumbai,0,53,19.31,279,No,1,4,368.32,Tuesday,4
4059,T104059,CUST3683,23-06-2023 01:18,385.89,Travel,NetBanking,POS,Mumbai,1,73,288.63,580,No,1,1,97.26,Friday,6
261,T100261,CUST6250,15-05-2023 04:10,368.85,Food,Credit Card,Mobile,Delhi,0,27,329.12,1426,No,1,4,39.73,Monday,5

# Fraud Ratio by Merchant Category

In [118]:
merchant_fraud = df.groupby(
    'Merchant_Category'
)['Fraudulent'].mean() * 100

fr = merchant_fraud.sort_values(
    ascending=False
)

fmc = pd.DataFrame(fr)
fmc

                   Fraudulent
Merchant_Category
Entertainment       11.428571
Food                10.818713
Fashion             10.197368
Health              10.066007
Travel               9.348915
Grocery              9.220986
Utilities            8.417508
Electronics          7.538462

# Fraud Ratio by Payment Method

In [123]:
payment_fraud = df.groupby(
    'Payment_Method'
)['Fraudulent'].mean() * 100

fp = payment_fraud.sort_values(
    ascending=False
)

fpm = pd.DataFrame(fp)
fpm

                Fraudulent
Payment_Method
UPI              10.405827
Debit Card       10.218254
Credit Card       9.876543
PayPal            9.589041
NetBanking        8.196721

# Fraud Ratio by Device Type

In [128]:
device_fraud = df.groupby(
    'Device_Type'
)['Fraudulent'].mean() * 100

fdr = device_fraud.sort_values(
    ascending=False
)

frd = pd.DataFrame(fdr)
frd

             Fraudulent
Device_Type
Desktop       10.244193
POS            9.503885
Mobile         9.162621